Repository openstax/cnx-recipes, pull requests merged in 2018-09, with the labels that each got.

#607 removed unnumbered equations config
  recipes/books/ap-physics/_config.scss
  recipes/output/ap-physics.css
Labels: question:Alina, review:Helene

#616 reverted changes in apphysics config
  recipes/books/ap-physics/_config.scss
  recipes/output/ap-physics.css
Labels: review:Helene

#423 Recipe change for toc alignment
  recipes/books/_feature.scss
  recipes/mixins/_toc.scss
  recipes/output/statistics.css
Labels: baked-PDF

#647 Issue-606
  FEATURES.md
  recipes/books/_feature.scss
  recipes/output/accounting.css
  recipes/output/entrepreneurship.css
  recipes/output/principles-management.css
Labels: review:Helene

#643 KatAW.senna.syrena
  recipes/books/ap-biology/_config.scss
  recipes/output/ap-biology.css
Labels: review:Helene
