Repository openstax/cnx-recipes, pull requests merged in 2018-10, with the labels that each got.

#621 Tables styles
  baked-book.pdf
  styles/framework/_import-mixins.scss
  styles/framework/config/_color-map.scss
  styles/framework/config/_settings.scss
  styles/framework/mixins/_tables.scss
  styles/output/intro-business.css
  styles/output/intro-business.css.map
  styles/themes/theme3/config/_settings.scss
  styles/themes/theme3/import-style.scss
  styles/themes/theme3/style/tables.scss
Labels: review:BrittanyJ

#433 SVG Icons, EOC, and Notes
  styles/books/intro-business/config/_icon-map.scss
  styles/books/intro-business/intro-business.scss
  styles/framework/_import-config.scss
  styles/framework/_update-config.scss
  styles/framework/config/_color-map.scss
  styles/framework/config/_color-scheme.scss
  styles/framework/config/_font-map.scss
  styles/framework/config/_icon-map.scss
  styles/framework/config/_settings.scss
  styles/framework/import-style.scss
  styles/framework/mixins/_notes.scss
  styles/framework/mixins/_titles.scss
  styles/framework/style/eob.scss
  styles/framework/style/eoc.scss
  styles/framework/style/modules.scss
  styles/output/intro-business.css
  styles/output/intro-business.css.map
  styles/themes/theme1/mixins/_color-map.scss
  styles/themes/theme3/config/_color-map.scss
  styles/themes/theme3/config/_color-scheme.scss
  styles/themes/theme3/config/_icon-map.scss
  styles/themes/theme3/config/_notes-schemes.scss
  styles/themes/theme3/config/_settings.scss
  styles/themes/theme3/images/assessments-icon.svg
  styles/themes/theme3/images/casestudy-icon.svg
  styles/themes/theme3/images/catching-spirit.svg
  styles/themes/theme3/images/ch-intro-icon.svg
  styles/themes/theme3/images/concept-check.svg
  styles/themes/theme3/images/figure-credit-icon.svg
  styles/themes/theme3/images/key-terms-icon.svg
  styles/themes/theme3/images/learn-obj-icon.svg
  styles/themes/theme3/images/link-to-learning.svg
  styles/themes/theme3/images/references-icon.svg
  styles/themes/theme3/images/suggested-resources-icon.svg
  styles/themes/theme3/images/summary-icon.svg
  styles/themes/theme3/images/thought-provoker-icon.svg
  styles/themes/theme3/images/toc-icon.svg
  styles/themes/theme3/images/unit-icon.svg
Labels: review:Helene

#694 Updated Intro to Business ID in books.txt
  books.txt
Labels: book:introduction.business
