Repository openstax/cnx-recipes, pull requests merged in 2018-08, with the labels that each got.

#528 Add glossary instead of key terms
  recipes/books/business-ethics/_config.scss
  recipes/output/business-ethics.css
Labels: review:BrittanyJ

#529 Issue 481
  recipes/books/business-ethics/_config.scss
  recipes/output/business-ethics.css
Labels: review:BrittanyJ, review:Damon

#530 Fix link to learning
  recipes/books/business-ethics/_config.scss
  recipes/output/business-ethics.css
Labels: review:BrittanyJ

#534 Enable End Notes support
  recipes/books/_common-stuff.scss
  recipes/books/_generator.scss
  recipes/books/business-ethics/_config.scss
  recipes/mixins/_count.scss
  recipes/mixins/_number.scss
  recipes/output/business-ethics.css
Labels: review:BrittanyJ

#535 Update .gitignore to ignore build files
  .gitignore
Labels: review:BrittanyJ

#578 Enable all feature flags
  FEATURES.md
  recipes/books/_feature.scss
  recipes/output/accounting.css
  recipes/output/ap-biology.css
  recipes/output/ap-physics.css
  recipes/output/biology.css
  recipes/output/business-ethics.css
  recipes/output/entrepreneurship.css
  recipes/output/intro-business.css
  recipes/output/physics.css
  recipes/output/principles-management.css
  recipes/output/statistics.css
Labels: review:Helene
