Repository openstax/cnx-recipes, pull requests merged in 2019-10, with the labels that each got.

#1421 Add style to Toc in Anatomy
  RELEASE_FLAGS.md
  recipes/books/_release.scss
  recipes/mixins/_toc.scss
  recipes/output/anatomy.css
  recipes/output/biology.css
  recipes/output/chemistry.css
  recipes/output/microbiology.css
  styles/books/anatomy/book.scss
  styles/designs/carnival/parts/_toc-components.scss
  styles/designs/carnival/parts/_toc-shapes.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/apbiology-pdf.css
  styles/output/apbiology-pdf.css.map
  styles/output/apbiology-rex-web.css
  styles/output/apbiology-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/microbiology-rex-web.css
  styles/output/microbiology-rex-web.css.map
  styles/templates/template1/_colors.scss
  styles/templates/template1/parts/_toc-settings.scss
Labels: review:BrittanyJ

#1434 Style eoc in Anatomy
  styles/books/anatomy/book.scss
  styles/designs/carnival/parts/_eoc-components.scss
  styles/designs/carnival/parts/_eoc-shapes.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/templates/template1/parts/_eoc-settings.scss
Labels: review:BrittanyJ

#1452 Style terms in anatomy
  styles/books/anatomy/book.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
Labels: review:Helene

#1451 Style links in anatomy
  styles/books/anatomy/book.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
Labels: review:Helene

#1458 issue-1341 pt 2
  styles/books/anatomy/book.scss
  styles/books/biology/book.scss
  styles/books/chemistry/book.scss
  styles/books/microbiology/book.scss
  styles/designs/carnival/parts/notes/_notes-components.scss
  styles/designs/carnival/parts/notes/_notes-iconCondensed-shapes.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/apbiology-pdf.css
  styles/output/apbiology-pdf.css.map
  styles/output/apbiology-rex-web.css
  styles/output/apbiology-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/microbiology-rex-web.css
  styles/output/microbiology-rex-web.css.map
Labels: review:Thomas

#1455 Clean up colors chemistry
  styles/books/chemistry/book.scss
  styles/output/_web-styles.json
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/templates/template1/_colors.scss
Labels: review:BrittanyJ

#1461 Check your understanding
  styles/books/microbiology/book.scss
  styles/designs/carnival/resources/carnival-check.svg
  styles/output/_web-styles.json
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/microbiology-rex-web.css
  styles/output/microbiology-rex-web.css.map
Labels: review:BrittanyJ

#1472 Style ToC in Physics
  RELEASE_FLAGS.md
  books.txt
  recipes/books/_release.scss
  recipes/books/physics/_config.scss
  recipes/output/physics.css
  styles/books/physics/book.scss
  styles/output/_web-styles.json
  styles/output/physics-pdf.css
  styles/output/physics-pdf.css.map
  styles/output/physics-rex-web.css
  styles/output/physics-rex-web.css.map
  styles/templates/template1/_colors.scss
Labels: review:Anna, review:BrittanyJ

#1441 Style Anatomy Introduction page
  RELEASE_FLAGS.md
  recipes/books/_release.scss
  recipes/mixins/_modify.scss
  recipes/output/anatomy.css
  styles/books/anatomy/book.scss
  styles/designs/carnival/parts/_chapterintro-components.scss
  styles/designs/carnival/parts/_chapterintro-shapes.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/templates/template1/_colors.scss
  styles/templates/template1/parts/_chapterintro-settings.scss
Labels: review:Thomas

#1456 Style figures in Anatomy
  styles/books/anatomy/book.scss
  styles/designs/carnival/parts/_chapterintro-components.scss
  styles/designs/carnival/parts/_figureimage-components.scss
  styles/designs/carnival/parts/_figureimage-shapes.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/microbiology-rex-web.css
  styles/output/microbiology-rex-web.css.map
  styles/templates/template1/parts/_chapterintro-settings.scss
  styles/templates/template1/parts/_figureimage-settings.scss
Labels: review:Anna, review:Thomas

#1525 Enable flags
  RELEASE_FLAGS.md
  recipes/books/_release.scss
  recipes/output/anatomy.css
  recipes/output/biology.css
  recipes/output/chemistry.css
  styles/output/_web-styles.json
Labels: review:Helene

#1443 Add color bands to EOB Appendix in chemistry
  styles/books/chemistry/book.scss
  styles/output/_web-styles.json
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
Labels: review: Natalia

#1540 Style introduction page in Biology & AP Biology
  RELEASE_FLAGS.md
  recipes/books/_release.scss
  recipes/output/ap-biology.css
  styles/books/biology/book.scss
  styles/output/_web-styles.json
  styles/output/apbiology-pdf.css
  styles/output/apbiology-pdf.css.map
  styles/output/apbiology-rex-web.css
  styles/output/apbiology-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
Labels: review: Natalia, review:BrittanyJ, review:Helene
