Repository openstax/cnx-recipes, pull requests merged in 2019-01, with the labels that each got.

#753 Section exercises numbering
  recipes/books/_generator.scss
  recipes/books/dev-math/_config.scss
  recipes/mixins/_compose.scss
  recipes/output/dev-math.css
Labels: review:Adrian, review:Helene

#756 Fix wrong exercise link label
  recipes/books/dev-math/_config.scss
  recipes/output/dev-math.css
Labels: review:Helene

#772 trash abstract in the preface feature for anatomy
  FEATURES.md
  recipes/books/_feature.scss
  recipes/books/_generator.scss
  recipes/output/anatomy-physiology.css
Labels: review:Helene

#773 turned off feature preface-has-captions
  FEATURES.md
  recipes/books/_feature.scss
  recipes/output/anatomy-physiology.css
Labels: review:Helene

#774 removed double headers from notes
  recipes/books/anatomy-physiology/_config.scss
  recipes/output/anatomy-physiology.css
Labels: review:Helene

#775 added answer key and trashed half solutions
  recipes/books/anatomy-physiology/_config.scss
  recipes/output/anatomy-physiology.css
Labels: review:Helene

#779 added references to the eob
  recipes/books/anatomy-physiology/_config.scss
  recipes/output/anatomy-physiology.css
Labels: review:Helene

#769 Add dot after number in references
  recipes/mixins/_number.scss
  recipes/output/american-government.css
  recipes/output/intro-business.css
  recipes/output/principles-management.css
Labels: review:Adrian

#748 Dev-math Recipe
  recipes/books/_common-stuff.scss
  recipes/books/_generator.scss
  recipes/books/dev-math/_config.scss
  recipes/mixins/_compose.scss
  recipes/mixins/_count.scss
  recipes/mixins/_number.scss
  recipes/output/dev-math.css
Labels: book:elementary.algebra
