Repository openstax/cnx-recipes, pull requests merged in 2019-02, with the labels that each got.

#696 Baked-PDF Styling Docs
  styles/books/intro-business/book.scss
  styles/framework/config/_color-scheme.scss
  styles/styling-bakedpdf.md
Labels: review:Thomas

#850 change a:link to a[href]
  styles/framework/base.scss
  styles/framework/import-style.scss
  styles/framework/mixins/_notes.scss
  styles/output/intro-business-2.css
  styles/output/intro-business.css
  styles/themes/theme1/mixins/_notes.scss
  styles/themes/theme1/parts/eoc.scss
  styles/themes/theme1/parts/notes.scss
  styles/themes/theme1/theme.scss
  styles/themes/theme2/parts/eoc.scss
  styles/themes/theme2/parts/notes.scss
Labels: review:BrittanyJ, review:Helene, status:no.qa

#813 Implement normalize.css
  package.json
  styles/framework/import-style.scss
  styles/output/intro-business.css
  styles/output/intro-business.css.map
Labels: review:Helene, review:Thomas

#844 chore: rename compile-* and generate-* to build-*
  README.md
  books.txt
  recipes/README.md
  script/bake-book
  script/bake-book-remote
  script/build-and-update-gh-pages
  script/build-docs
  script/build-guide
  script/build-recipes
  script/diff-guide-prepare
  script/test
  styles/books/new-book.sh
Labels: review:BrittanyJ, status:no.qa

#871 changed numbering of try it notes
  recipes/books/precalculus/_config.scss
  recipes/output/precalculus.css
Labels: book:precalculus, review:Helene

#837 Section separated links for titles in eoc
  recipes/books/_feature.scss
  recipes/mixins/_compose.scss
  recipes/mixins/_modify.scss
  recipes/output/accounting.css
  recipes/output/american-government.css
  recipes/output/anatomy.css
  recipes/output/ap-biology.css
  recipes/output/ap-physics.css
  recipes/output/astronomy.css
  recipes/output/biology.css
  recipes/output/business-ethics.css
  recipes/output/chemistry.css
  recipes/output/dev-math.css
  recipes/output/economics.css
  recipes/output/entrepreneurship.css
  recipes/output/history.css
  recipes/output/intro-business.css
  recipes/output/microbiology.css
  recipes/output/physics.css
  recipes/output/principles-management.css
  recipes/output/psychology.css
  recipes/output/sociology.css
  recipes/output/statistics.css
  recipes/output/u-physics.css
Labels: review: Natalia, review:Adrian, review:BrittanyJ

#845 EOC & Answer Key composite chapters
  .gitignore
  FEATURES.md
  recipes/books/_common-stuff.scss
  recipes/books/_feature.scss
  recipes/books/accounting/_config.scss
  recipes/books/american-government/_config.scss
  recipes/books/ap-biology/_config.scss
  recipes/books/ap-physics/_config.scss
  recipes/books/astronomy/_config.scss
  recipes/books/biology/_config.scss
  recipes/books/business-ethics/_config.scss
  recipes/books/chemistry/_config.scss
  recipes/books/dev-math/_config.scss
  recipes/books/economics/_config.scss
  recipes/books/entrepreneurship/_config.scss
  recipes/books/history/_config.scss
  recipes/books/microbiology/_config.scss
  recipes/books/precalculus/_config.scss
  recipes/books/u-physics/_config.scss
  recipes/mixins/_compose.scss
  recipes/mixins/_modify.scss
  recipes/mixins/_toc.scss
  recipes/output/accounting.css
  recipes/output/american-government.css
  recipes/output/anatomy.css
  recipes/output/ap-biology.css
  recipes/output/ap-physics.css
  recipes/output/astronomy.css
  recipes/output/biology.css
  recipes/output/business-ethics.css
  recipes/output/chemistry.css
  recipes/output/dev-math.css
  recipes/output/economics.css
  recipes/output/entrepreneurship.css
  recipes/output/history.css
  recipes/output/intro-business.css
  recipes/output/microbiology.css
  recipes/output/physics.css
  recipes/output/principles-management.css
  recipes/output/psychology.css
  recipes/output/sociology.css
  recipes/output/statistics.css
  recipes/output/u-physics.css
Labels: review: Natalia, review:Adrian, review:BrittanyJ

#875 issue-834
  recipes/books/principles-management/_config.scss
  recipes/output/principles-management.css
Labels: review:Helene

#887 Remove completed release flags
  RELEASE_FLAGS.md
  recipes/books/_generator.scss
  recipes/books/_release.scss
  recipes/mixins/_link.scss
  recipes/mixins/_modify.scss
  recipes/mixins/_number.scss
Labels: status:no.qa

#886 Remove numbering-continuously flag
  RELEASE_FLAGS.md
  recipes/books/_generator.scss
  recipes/books/_release.scss
Labels: status:no.qa

#882 Remove answerkey apbiology
  recipes/books/ap-biology/_config.scss
  recipes/output/ap-biology.css
Labels: book:ap.biology
