Repository openstax/cnx-recipes, pull requests merged in 2019-07, with the labels that each got.

#1173 Restructuring styles directory
  styles/books/chemistry/book.scss
  styles/designs/common/web/_common-components.scss
  styles/designs/common/web/_common-spaces.scss
  styles/templates/carnival/carnival.scss
  styles/templates/generic/_design.scss
  styles/templates/generic/generic.scss
  styles/templates/template1/_colors.scss
  styles/templates/template1/_design.scss
  styles/templates/template1/_settings.scss
  styles/templates/template1/_typography.scss
  styles/templates/template1/parts/_eoc-settings.scss
  styles/templates/template1/parts/_learning-settings.scss
  styles/templates/template1/template1.scss
Labels: review:Thomas

#1161 Notes: Parts and Settings #1079 #1082 #1087 #1088 #1089 #1090
  styles/books/chemistry/book.scss
  styles/designs/carnival/parts/_borderfeature-components.scss
  styles/designs/carnival/parts/_borderfeature-spaces.scss
  styles/designs/carnival/parts/_iconfeature-components.scss
  styles/designs/carnival/parts/_iconfeature-spaces.scss
  styles/designs/carnival/parts/_linktolearning-components.scss
  styles/designs/carnival/parts/_linktolearning-spaces.scss
  styles/designs/carnival/resources/carnival-example.svg
  styles/designs/carnival/resources/carnival-interconnect.svg
  styles/designs/carnival/resources/carnival-linktolearning.svg
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/templates/generic/_design.scss
  styles/templates/template1/_colors.scss
  styles/templates/template1/_design.scss
  styles/templates/template1/_settings.scss
  styles/templates/template1/_typography.scss
  styles/templates/template1/parts/_everyday-settings.scss
  styles/templates/template1/parts/_example-settings.scss
  styles/templates/template1/parts/_interconnect-settings.scss
  styles/templates/template1/parts/_learning-settings.scss
  styles/templates/template1/parts/_linktolearning-settings.scss
  styles/templates/template1/parts/_portrait-settings.scss
Labels: review:Thomas

#1198 Fixes to the Icons to (Hopefully)
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/templates/template1/parts/_linktolearning-settings.scss
Labels: review:Thomas

#1131 Issue #1085
  styles/books/chemistry/book.scss
  styles/designs/carnival/parts/_eoc-components.scss
  styles/designs/carnival/parts/_eoc-spaces.scss
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/templates/generic/_design.scss
  styles/templates/template1/_colors.scss
  styles/templates/template1/_design.scss
  styles/templates/template1/_settings.scss
  styles/templates/template1/_typography.scss
  styles/templates/template1/parts/_eoc-settings.scss
Labels: review:Helene

#1209 Fixing Icons: How Sciences Interconnect
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/templates/template1/parts/_interconnect-settings.scss
Labels: review:Thomas

#1188 Issue 1073
  styles/books/chemistry/book.scss
  styles/designs/carnival/parts/_preface-components.scss
  styles/designs/carnival/parts/_preface-spaces.scss
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/output/intro-business-pdf.css
  styles/output/intro-business-pdf.css.map
  styles/output/intro-business-rex-web.css
  styles/output/intro-business-rex-web.css.map
  styles/templates/template1/_colors.scss
  styles/templates/template1/_design.scss
  styles/templates/template1/_settings.scss
  styles/templates/template1/parts/_preface-settings.scss
Labels: review:Helene

#1212 Update readme with run command fo docker documentation
  README.md
Labels: review:Thomas

#1239 Carnival Answer Key
  styles/books/chemistry/book.scss
  styles/designs/carnival/parts/_answerkey-components.scss
  styles/designs/carnival/parts/_answerkey-shapes.scss
  styles/designs/carnival/parts/_index-components.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/templates/template1/_design.scss
  styles/templates/template1/_settings.scss
  styles/templates/template1/_typography.scss
  styles/templates/template1/parts/_answerkey-settings.scss
  styles/templates/template1/parts/_example-settings.scss
  styles/templates/template1/parts/_index-settings.scss
  styles/templates/template1/parts/_interconnect-settings.scss
Labels: review:Thomas

#1248 Issue 1081 new2
  styles/output/_web-styles.json
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/templates/template1/parts/_figureimage-settings.scss
Labels: review:BrittanyJ
