Repository openstax/cnx-recipes, pull requests merged in 2019-09, with the labels that each got.

#1337 Scale and rhythm overhaul
  styles/designs/carnival/parts/_answerkey-components.scss
  styles/designs/carnival/parts/_borderfeature-components.scss
  styles/designs/carnival/parts/_borderfeature-shapes.scss
  styles/designs/carnival/parts/_eoc-components.scss
  styles/designs/carnival/parts/_iconfeature-components.scss
  styles/designs/carnival/parts/_index-components.scss
  styles/designs/carnival/parts/_index-shapes.scss
  styles/designs/carnival/parts/_linktolearning-components.scss
  styles/designs/carnival/parts/_linktolearning-shapes.scss
  styles/designs/carnival/parts/_module-components.scss
  styles/designs/common/_reset.scss
  styles/designs/common/pdf/_grid.scss
  styles/designs/common/pdf/typography.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/microbiology-rex-web.css
  styles/output/microbiology-rex-web.css.map
  styles/templates/template1/_typography.scss
  styles/templates/template1/parts/_answerkey-settings.scss
  styles/templates/template1/parts/_example-settings.scss
  styles/templates/template1/parts/_index-settings.scss
  styles/templates/template1/parts/_interconnect-settings.scss
  styles/templates/template1/parts/_linktolearning-settings.scss
  styles/templates/template1/parts/_module-settings.scss
  styles/templates/template1/parts/_portrait-settings.scss
Labels: review:Thomas

#1326 Refactor Answer Key components
  styles/designs/carnival/parts/_answerkey-components.scss
  styles/designs/carnival/parts/_answerkey-shapes.scss
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css.map
Labels: review:BrittanyJ

#1371 V align math
  styles/designs/common/_reset.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/apbiology-pdf.css
  styles/output/apbiology-pdf.css.map
  styles/output/apbiology-rex-web.css
  styles/output/apbiology-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/microbiology-rex-web.css
  styles/output/microbiology-rex-web.css.map
Labels: review:Thomas

#1372 Fix sup and sub scripts line height
  styles/designs/common/_reset.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/apbiology-pdf.css
  styles/output/apbiology-pdf.css.map
  styles/output/apbiology-rex-web.css
  styles/output/apbiology-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/microbiology-rex-web.css
  styles/output/microbiology-rex-web.css.map
Labels: review: Natalia

#1404 Add twine check on travis
  script/ci
Labels: review:BrittanyJ, review:Thomas

#1390 Issue 1280
  books.txt
  recipes/books/_release.scss
  recipes/output/microbiology.css
  styles/books/anatomy/book.scss
  styles/books/biology/book.scss
  styles/books/chemistry/book.scss
  styles/books/microbiology/book.scss
  styles/designs/carnival/parts/_chapter-components.scss
  styles/designs/carnival/parts/_chapter-shapes.scss
  styles/designs/carnival/parts/_eoc-components.scss
  styles/designs/carnival/parts/_eoc-shapes.scss
  styles/designs/carnival/parts/_learning-components.scss
  styles/designs/carnival/parts/_learning-shapes.scss
  styles/output/_web-styles.json
  styles/output/apbiology-pdf.css
  styles/output/apbiology-pdf.css.map
  styles/output/apbiology-rex-web.css
  styles/output/apbiology-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/microbiology-rex-web.css
  styles/output/microbiology-rex-web.css.map
  styles/templates/template1/_colors.scss
  styles/templates/template1/parts/_eoc-settings.scss
  styles/templates/template1/parts/_learning-settings.scss
Labels: review:Helene, review:Thomas

#1393 Add styling for preface in anatomy
  recipes/output/microbiology.css
  styles/books/anatomy/book.scss
  styles/books/biology/book.scss
  styles/books/chemistry/book.scss
  styles/books/microbiology/book.scss
  styles/designs/carnival/parts/_preface-components.scss
  styles/designs/carnival/parts/_preface-shapes.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/apbiology-pdf.css.map
  styles/output/apbiology-rex-web.css.map
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css.map
  styles/output/microbiology-pdf.css.map
  styles/output/microbiology-rex-web.css.map
  styles/templates/template1/_settings.scss
  styles/templates/template1/parts/_preface-settings.scss
Labels: review:Thomas

#1397 Add style to module headers in anatomy
  styles/books/anatomy/book.scss
  styles/books/chemistry/book.scss
  styles/books/microbiology/book.scss
  styles/designs/carnival/parts/_module-components.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/apbiology-pdf.css.map
  styles/output/apbiology-rex-web.css.map
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css.map
  styles/output/microbiology-pdf.css.map
  styles/output/microbiology-rex-web.css.map
  styles/templates/template1/_settings.scss
  styles/templates/template1/parts/_module-settings.scss
Labels: review:Thomas

#1399 Add style to chapter title in anatomy
  books.txt
  recipes/output/anatomy.css
  styles/books/anatomy/book.scss
  styles/books/chemistry/book.scss
  styles/books/microbiology/book.scss
  styles/designs/carnival/parts/_chapter-components.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/apbiology-pdf.css.map
  styles/output/apbiology-rex-web.css.map
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/microbiology-rex-web.css
  styles/output/microbiology-rex-web.css.map
  styles/templates/template1/_settings.scss
  styles/templates/template1/parts/_chapter-settings.scss
Labels: review:Thomas

#1424 Review comments from #1411
  styles/designs/carnival/parts/notes/_notes-components.scss
  styles/output/_web-styles.json
Labels: review:Helene, status:no.qa
