Repository openstax/cnx-recipes, pull requests merged in 2019-06, with the labels that each got.

#1094 Easybake/cnx-recipes tutorial
  docs/tutorial/01-moveto-raw.html
  docs/tutorial/02-create-content-raw.html
  docs/tutorial/02-create-nested-content-baked.html
  docs/tutorial/03-passes-raw.html
  docs/tutorial/04-numbering-baked.html
  docs/tutorial/04-numbering-raw.html
  docs/tutorial/05-target-label-baked.html
  docs/tutorial/05-target-label.html
  docs/tutorial/06-nesting-quirks-baked.html
  docs/tutorial/06-nesting-quirks.html
  docs/tutorial/simple-page.html
Labels: status:no.qa

#1021 Add support for creating multiple indexes
  recipes/books/_generator.scss
  recipes/mixins/_compose.scss
  recipes/mixins/_enums.scss
  recipes/output/accounting.css
  recipes/output/american-government.css
  recipes/output/anatomy.css
  recipes/output/ap-biology.css
  recipes/output/ap-physics.css
  recipes/output/astronomy.css
  recipes/output/biology.css
  recipes/output/business-ethics.css
  recipes/output/calculus.css
  recipes/output/chemistry.css
  recipes/output/dev-math.css
  recipes/output/economics.css
  recipes/output/entrepreneurship.css
  recipes/output/history.css
  recipes/output/intro-business.css
  recipes/output/microbiology.css
  recipes/output/physics.css
  recipes/output/precalculus.css
  recipes/output/principles-management.css
  recipes/output/psychology.css
  recipes/output/sociology.css
  recipes/output/statistics.css
  recipes/output/u-physics.css
Labels: review:Helene

#1123 Redo: Update style framework docs to include new concepts
  styles/styling-bakedpdf.md
Labels: status:no.qa

#1125 #1103 Add missing & to the title
  recipes/books/precalculus/_config.scss
  recipes/output/precalculus.css
Labels: book:precalculus

#1129 Scaffolding
  .gitignore
  styles/books/generic/book.scss
  styles/designs/common/pdf/_common-components.scss
  styles/designs/common/pdf/_common-spaces.scss
  styles/output/generic-pdf.css
  styles/output/generic-pdf.css.map
  styles/templates/generic/_colors.scss
  styles/templates/generic/_settings.scss
  styles/templates/generic/_typography.scss
  styles/templates/generic/design.scss
  styles/templates/generic/generic.scss
Labels: review: Natalia

#1135 #1105 Custom footnote numbering
  recipes/books/_common-stuff.scss
  recipes/books/_generator.scss
  recipes/books/precalculus/_config.scss
  recipes/mixins/_count.scss
  recipes/mixins/_modify.scss
  recipes/mixins/_number.scss
  recipes/output/precalculus.css
Labels: book:precalculus, review:BrittanyJ

#1150 Template structure
  styles/templates/carnival/_colors.scss
  styles/templates/carnival/_settings.scss
  styles/templates/carnival/_typography.scss
  styles/templates/carnival/carnival.scss
  styles/templates/carnival/design.scss
  styles/templates/carnival/parts/_eoc-settings.scss
Labels: review:Thomas

#1119 issue-1059
  .node-version
  js/build-style/build-style.js
  recipes/build/build.js
  script/build-recipes
Labels: review:Thomas

#1130 Learning Objectives with Thomas' comments added
  styles/books/chemistry/book.scss
  styles/designs/carnival/parts/_learning-components.scss
  styles/designs/carnival/parts/_learning-spaces.scss
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/templates/carnival/_colors.scss
  styles/templates/carnival/parts/_learning-settings.scss
Labels: review:BrittanyJ
