Repository openstax/cnx-recipes, pull requests merged in 2019-08, with the labels that each got.

#1254 Fixes to font sizes
  styles/designs/carnival/parts/_answerkey-components.scss
  styles/output/_web-styles.json
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/templates/template1/parts/_answerkey-settings.scss
Labels: review:BrittanyJ, review:Thomas

#1256 Fix css files going out of sync
  script/bake-book
Labels: status:no.qa

#1253 Issue 1157
  styles/books/biology/book.scss
  styles/output/_web-styles.json
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/templates/template1/_settings.scss
  styles/templates/template1/parts/_everyday2-settings.scss
Labels: review:BrittanyJ, review:Helene

#1255 Issue 1081 new2
  styles/output/_web-styles.json
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/templates/template1/_typography.scss
  styles/templates/template1/parts/_figureimage-settings.scss
Labels: review:Helene

#1199 Issue 1064
  RELEASE_FLAGS.md
  recipes/books/_generator.scss
  recipes/books/_release.scss
  recipes/build/build.js
  recipes/mixins/_modify.scss
  recipes/output/chemistry.css
Labels: review: Natalia, review:Helene, review:Thomas

#1269 Implement font-scale, line-height and vertical-rythm scales
  styles/designs/carnival/parts/_index-components.scss
  styles/designs/common/pdf/typography.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/templates/template1/_typography.scss
  styles/templates/template1/parts/_index-settings.scss
Labels: review: Natalia

#1271 Font scale implementation
  styles/designs/carnival/parts/_answerkey-components.scss
  styles/designs/carnival/parts/_appendix-components.scss
  styles/designs/carnival/parts/_borderfeature-components.scss
  styles/designs/carnival/parts/_iconfeature-components.scss
  styles/designs/carnival/parts/_linktolearning-components.scss
  styles/designs/carnival/parts/_preface-components.scss
  styles/designs/carnival/parts/_references-components.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/templates/template1/_typography.scss
  styles/templates/template1/parts/_answerkey-settings.scss
  styles/templates/template1/parts/_appendix-settings.scss
  styles/templates/template1/parts/_career-settings.scss
  styles/templates/template1/parts/_example-settings.scss
  styles/templates/template1/parts/_iconfeatures-settings.scss
  styles/templates/template1/parts/_interconnect-settings.scss
  styles/templates/template1/parts/_learning-settings.scss
  styles/templates/template1/parts/_linktolearning-settings.scss
  styles/templates/template1/parts/_preface-settings.scss
  styles/templates/template1/parts/_references-settings.scss
Labels: review: Natalia

#1266 Allow pdf docker-compose service to find styles/icons
  script/bake-book
  script/build-pdf
Labels: review: Natalia

#1268 Issue 1078
  styles/books/chemistry/book.scss
  styles/designs/carnival/parts/_chapterintro-components.scss
  styles/designs/carnival/parts/_chapterintro-shapes.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/templates/template1/_colors.scss
  styles/templates/template1/_design.scss
  styles/templates/template1/_settings.scss
  styles/templates/template1/_typography.scss
  styles/templates/template1/parts/_chapterintro-settings.scss
Labels: review:Helene

#1273 Horizontal rhythm
  styles/designs/common/pdf/_common-figure-components.scss
  styles/designs/common/pdf/_grid.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/templates/template1/_design.scss
  styles/templates/template1/parts/_common-figure-settings.scss
  styles/templates/template1/parts/_index-settings.scss
Labels: review: Natalia

#1282 Grid
  styles/designs/common/pdf/_grid.scss
  styles/designs/common/pdf/typography.scss
  styles/templates/template1/parts/_index-settings.scss
Labels: review: Natalia, review:Thomas

#1281 Splash styles
  styles/books/chemistry/book.scss
  styles/designs/carnival/parts/_chapter-components.scss
  styles/designs/carnival/parts/_chapter-shapes.scss
  styles/designs/carnival/parts/_chapterintro-components.scss
  styles/designs/carnival/parts/_chapterintro-shapes.scss
  styles/designs/carnival/parts/_figureimage-components.scss
  styles/designs/carnival/parts/_figureimage-shapes.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css.map
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/templates/template1/_colors.scss
  styles/templates/template1/_design.scss
  styles/templates/template1/_settings.scss
  styles/templates/template1/_typography.scss
  styles/templates/template1/parts/_chapter-settings.scss
  styles/templates/template1/parts/_chapterintro-settings.scss
  styles/templates/template1/parts/_figureimage-settings.scss
Labels: review:BrittanyJ

#1294 EOC extravaganza
  styles/designs/carnival/parts/_eoc-components.scss
  styles/designs/carnival/parts/_eoc-shapes.scss
  styles/designs/common/pdf/_reset.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/templates/template1/_colors.scss
  styles/templates/template1/parts/_eoc-settings.scss
Labels: review: Natalia

#1293 Fix formatting & naming warnings
  styles/books/anatomy/book.scss
  styles/books/biology/book.scss
  styles/books/chemistry/book.scss
  styles/designs/carnival/parts/_learning-components.scss
  styles/designs/carnival/parts/_learning-shapes.scss
  styles/output/_web-styles.json
  styles/templates/template1/parts/_learning-settings.scss
Labels: status:no.qa

#1297 Learning objectives styling
  styles/designs/carnival/parts/_learning-components.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/templates/template1/_colors.scss
  styles/templates/template1/parts/_learning-settings.scss
Labels: review: Natalia, review:Thomas

#1298 Change body font to Aleygria
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/templates/template1/_settings.scss
Labels: review: Natalia, review:Thomas

#1276 Fix bakery commands unable to access style file
  docker-compose.yml
  script/assemble-book
  script/bake-book
  script/build-pdf
  script/fetch-book
  script/mathify-book
Labels: review:Helene

#1328 Remove Learnig Objective comment
  styles/designs/carnival/parts/_appendix-components.scss
  styles/designs/carnival/parts/_borderfeature-components.scss
  styles/designs/carnival/parts/_iconfeature-components.scss
  styles/designs/carnival/parts/_index-components.scss
  styles/designs/carnival/parts/_linktolearning-components.scss
  styles/designs/carnival/parts/_references-components.scss
Labels: review:BrittanyJ

#1316 Change bottom padding to bottom margin for reset
  styles/designs/common/pdf/_reset.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
Labels: review:BrittanyJ

#1335 Move generated content to recipes
  Dockerfile
  books.txt
  recipes/books/_common-stuff.scss
  recipes/output/chemistry.css
  script/build-recipes
  script/build-styles
  styles/designs/carnival/parts/_appendix-components.scss
  styles/designs/carnival/parts/_appendix-shapes.scss
  styles/designs/carnival/parts/_chapter-components.scss
  styles/designs/carnival/parts/_toc-components.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/templates/template1/parts/_appendix-settings.scss
Labels: review:BrittanyJ, review:Helene
