Repository openstax/cnx-recipes, pull requests merged in 2020-01, with the labels that each got.

#1463 Style table in Anatomy
  RELEASE_FLAGS.md
  recipes/books/_generator.scss
  recipes/books/_release.scss
  recipes/books/chemistry/_config.scss
  recipes/mixins/_number.scss
  recipes/output/anatomy.css
  recipes/output/chemistry.css
  styles/books/anatomy/book.scss
  styles/books/chemistry/book.scss
  styles/designs/carnival/parts/_table-components.scss
  styles/designs/carnival/parts/_table-shapes.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/templates/template1/_colors.scss
  styles/templates/template1/parts/_table-settings.scss
Labels: review:Anna, review:BrittanyJ, review:Helene

#1715 Section links in composite chapters
  RELEASE_FLAGS.md
  recipes/books/_release.scss
  recipes/mixins/_compose.scss
  recipes/output/u-physics.css
  styles/output/_web-styles.json
Labels: review:Alan, review:Anna

#1744 Change data for hs physics in books.txt
  books.txt
Labels: review:Anna

#1710 u-physics-vol1: add style to learning objectives
  styles/books/u-physics/book.scss
  styles/output/_web-styles.json
  styles/output/u-physics-pdf.css
  styles/output/u-physics-pdf.css.map
  styles/output/u-physics-rex-web.css
  styles/output/u-physics-rex-web.css.map
Labels: book:university.physics, review:Alan

#1713 u-physics-vol1: add styles to figures
  styles/books/u-physics/book.scss
  styles/output/_web-styles.json
  styles/output/u-physics-pdf.css
  styles/output/u-physics-pdf.css.map
  styles/output/u-physics-rex-web.css
  styles/output/u-physics-rex-web.css.map
Labels: book:university.physics, review:Alan

#1707 HS Physics EOC
  RELEASE_FLAGS.md
  recipes/books/_release.scss
  recipes/books/hs-physics/_config.scss
  recipes/mixins/_compose.scss
  recipes/output/hs-physics.css
  styles/output/_web-styles.json
Labels: review:Alan, review:Anna, review:BrittanyJ

#1732 u-physics-vol1: add styles problem-solving note u-physics-vol1
  styles/books/u-physics/book.scss
  styles/designs/carnival/resources/carnival-problemsolving.svg
  styles/output/_web-styles.json
  styles/output/u-physics-pdf.css
  styles/output/u-physics-pdf.css.map
  styles/output/u-physics-rex-web.css
  styles/output/u-physics-rex-web.css.map
  styles/templates/template1/_colors.scss
Labels: book:university.physics, review:Alan

#1734 link to learnin note u-physics-vol1
  styles/books/u-physics/book.scss
  styles/output/_web-styles.json
  styles/output/u-physics-pdf.css
  styles/output/u-physics-pdf.css.map
  styles/output/u-physics-rex-web.css
  styles/output/u-physics-rex-web.css.map
Labels: book:university.physics, review:Alan

#1736 uphysics vol1: style check your understanding note
  styles/books/u-physics/book.scss
  styles/designs/carnival/parts/notes/_notes-components.scss
  styles/designs/carnival/parts/notes/_notes-iconCondensed-shapes.scss
  styles/output/_web-styles.json
  styles/output/u-physics-pdf.css
  styles/output/u-physics-pdf.css.map
  styles/output/u-physics-rex-web.css
  styles/output/u-physics-rex-web.css.map
Labels: book:university.physics, review:Alan

#1738 u-physics vol1: introduction page
  RELEASE_FLAGS.md
  recipes/books/_release.scss
  recipes/output/u-physics.css
  styles/books/u-physics/book.scss
  styles/output/_web-styles.json
  styles/output/u-physics-pdf.css
  styles/output/u-physics-pdf.css.map
  styles/output/u-physics-rex-web.css
  styles/output/u-physics-rex-web.css.map
Labels: book:university.physics, review:Alan

#1748 Move Problems to EOC in HS Physics
  recipes/books/hs-physics/_config.scss
  recipes/output/hs-physics.css
Labels: review:Anna

#1659 Style EOB and EOC in Physics
  styles/books/anatomy/book.scss
  styles/books/biology/book.scss
  styles/books/chemistry/book.scss
  styles/books/microbiology/book.scss
  styles/books/physics/book.scss
  styles/designs/carnival/parts/_eoc-components.scss
  styles/designs/carnival/parts/_eoc-shapes.scss
  styles/output/_web-styles.json
  styles/output/physics-pdf.css
  styles/output/physics-pdf.css.map
  styles/output/physics-rex-web.css
  styles/output/physics-rex-web.css.map
  styles/templates/template1/parts/_eoc-settings.scss
Labels: review:Alan, review:Anna

#1756 u-physics-vol1: style appendix answer key
  styles/books/u-physics/book.scss
  styles/designs/carnival/parts/_answerkey-components.scss
  styles/output/_web-styles.json
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/microbiology-rex-web.css
  styles/output/microbiology-rex-web.css.map
  styles/output/u-physics-pdf.css
  styles/output/u-physics-pdf.css.map
  styles/output/u-physics-rex-web.css
  styles/output/u-physics-rex-web.css.map
  styles/templates/template1/parts/_answerkey-settings.scss
Labels: book:university.physics

#1754 u-physics vol1: add style to default notes examples
  styles/books/u-physics/book.scss
  styles/designs/carnival/parts/notes/_notes-components.scss
  styles/output/_web-styles.json
  styles/output/u-physics-pdf.css
  styles/output/u-physics-pdf.css.map
  styles/output/u-physics-rex-web.css
  styles/output/u-physics-rex-web.css.map
Labels: book:university.physics

#1761 Missing solutions in HS Physics
  recipes/books/hs-physics/_config.scss
  recipes/output/hs-physics.css
  styles/output/_web-styles.json
Labels: review:Anna

#1764 Numbered equations in hs physics
  recipes/books/hs-physics/_config.scss
  recipes/output/hs-physics.css
  styles/output/_web-styles.json
Labels: review:Anna

#1750 Issue 1370
  styles/designs/carnival/parts/_eoc-components.scss
  styles/designs/carnival/parts/_eoc-shapes.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/ap-biology-pdf.css
  styles/output/ap-biology-pdf.css.map
  styles/output/ap-biology-rex-web.css
  styles/output/ap-biology-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
Labels: review:Anna

#1768 Fix bad merge
  styles/designs/carnival/parts/_eoc-shapes.scss
  styles/output/_web-styles.json
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css.map
  styles/output/physics-pdf.css
  styles/output/physics-pdf.css.map
  styles/output/physics-rex-web.css
  styles/output/physics-rex-web.css.map
Labels: review:Anna

#1708 enable toc-eoc-composite-chapter flag microbiology
  RELEASE_FLAGS.md
  recipes/books/_release.scss
  recipes/output/microbiology.css
  styles/designs/carnival/parts/_toc-components.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/ap-biology-pdf.css
  styles/output/ap-biology-pdf.css.map
  styles/output/ap-biology-rex-web.css
  styles/output/ap-biology-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/microbiology-rex-web.css
  styles/output/microbiology-rex-web.css.map
  styles/output/physics-pdf.css
  styles/output/physics-pdf.css.map
  styles/output/physics-rex-web.css
  styles/output/physics-rex-web.css.map
  styles/output/u-physics-pdf.css
  styles/output/u-physics-pdf.css.map
  styles/output/u-physics-rex-web.css
  styles/output/u-physics-rex-web.css.map
Labels: book:microbiology

#1727 Equations u physics
  recipes/books/u-physics/_config.scss
  recipes/output/u-physics.css
  styles/books/u-physics/book.scss
  styles/designs/carnival/parts/_equation-components.scss
  styles/designs/carnival/parts/notes/_notes-boxedCondensed-shapes.scss
  styles/designs/carnival/parts/notes/_notes-components.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css.map
  styles/output/ap-biology-pdf.css
  styles/output/ap-biology-pdf.css.map
  styles/output/ap-biology-rex-web.css
  styles/output/ap-biology-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/output/microbiology-pdf.css.map
  styles/output/microbiology-rex-web.css.map
  styles/output/physics-pdf.css
  styles/output/physics-pdf.css.map
  styles/output/physics-rex-web.css
  styles/output/physics-rex-web.css.map
  styles/output/u-physics-pdf.css
  styles/output/u-physics-pdf.css.map
  styles/output/u-physics-rex-web.css
  styles/output/u-physics-rex-web.css.map
  styles/templates/template1/_colors.scss
  styles/templates/template1/_design.scss
  styles/templates/template1/parts/_equation-settings.scss
Labels: book:university.physics

#1648 REVIEW: Add conversion function from image url to data uri
  js/check-embedded-images/check-embedded-images.js
  package.json
  script/test
  styles/books/anatomy/book.scss
  styles/books/ap-biology/book.scss
  styles/books/biology/book.scss
  styles/books/chemistry/book.scss
  styles/books/microbiology/book.scss
  styles/books/physics/book.scss
  styles/books/u-physics/book.scss
  styles/build/build.js
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/ap-biology-pdf.css
  styles/output/ap-biology-pdf.css.map
  styles/output/ap-biology-rex-web.css
  styles/output/ap-biology-rex-web.css.map
  styles/output/apbiology-pdf.css
  styles/output/apbiology-pdf.css.map
  styles/output/apbiology-rex-web.css
  styles/output/apbiology-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/microbiology-rex-web.css
  styles/output/microbiology-rex-web.css.map
  styles/output/physics-pdf.css
  styles/output/physics-pdf.css.map
  styles/output/physics-rex-web.css
  styles/output/physics-rex-web.css.map
  styles/output/u-physics-pdf.css
  styles/output/u-physics-pdf.css.map
  styles/output/u-physics-rex-web.css
  styles/output/u-physics-rex-web.css.map
  yarn.lock
Labels: review:Helene

#1772 Style Introduction in HS Physics
  RELEASE_FLAGS.md
  books.txt
  recipes/books/_common-stuff.scss
  recipes/books/_release.scss
  recipes/books/hs-physics/_config.scss
  recipes/mixins/_modify.scss
  recipes/output/hs-physics.css
  styles/books/hs-physics/book.scss
  styles/output/_web-styles.json
  styles/output/hs-physics-pdf.css
  styles/output/hs-physics-pdf.css.map
  styles/output/hs-physics-rex-web.css
  styles/output/hs-physics-rex-web.css.map
Labels: review:Anna

#1775 Style titles in hs physics
  styles/books/hs-physics/book.scss
  styles/output/_web-styles.json
  styles/output/hs-physics-pdf.css
  styles/output/hs-physics-pdf.css.map
  styles/output/hs-physics-rex-web.css
  styles/output/hs-physics-rex-web.css.map
Labels: review:Anna

#1779 Style Preface in hs physics
  styles/books/hs-physics/book.scss
  styles/output/_web-styles.json
  styles/output/hs-physics-pdf.css
  styles/output/hs-physics-pdf.css.map
  styles/output/hs-physics-rex-web.css
  styles/output/hs-physics-rex-web.css.map
Labels: review:Anna

#1810 Report neb fetch cli flags
  script/fetch-book
Labels: review:Helene

#1799 Style learning objectives in HS Physics
  styles/books/hs-physics/book.scss
  styles/designs/carnival/parts/_learning-components.scss
  styles/designs/carnival/parts/_learning-shapes.scss
  styles/output/_web-styles.json
  styles/output/hs-physics-pdf.css
  styles/output/hs-physics-pdf.css.map
  styles/output/hs-physics-rex-web.css
  styles/output/hs-physics-rex-web.css.map
  styles/templates/template1/_colors.scss
  styles/templates/template1/parts/_learning-settings.scss
Labels: review:Anna

#1800 Issue 1794
  RELEASE_FLAGS.md
  recipes/books/_release.scss
  recipes/output/anatomy.css
  recipes/output/ap-biology.css
  recipes/output/ap-physics.css
  recipes/output/biology.css
  recipes/output/chemistry.css
  recipes/output/hs-physics.css
  recipes/output/microbiology.css
  recipes/output/physics.css
  recipes/output/u-physics.css
  styles/output/_web-styles.json
Labels: baked.styles, review:Anna

#1819 apbiology: scientific method connection note
  styles/books/ap-biology/book.scss
  styles/output/_web-styles.json
  styles/output/ap-biology-pdf.css
  styles/output/ap-biology-pdf.css.map
  styles/output/ap-biology-rex-web.css
  styles/output/ap-biology-rex-web.css.map
Labels: book:ap.biology

#1836 biology 2e: add Iframe to hidden
  styles/books/biology/book.scss
  styles/output/_web-styles.json
  styles/output/ap-biology-pdf.css
  styles/output/ap-biology-pdf.css.map
  styles/output/ap-biology-rex-web.css
  styles/output/ap-biology-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
Labels: book:biology.2e
