Repository openstax/cnx-recipes, pull requests merged in 2020-02, with the labels that each got.

#1834 Hs physics eoc eob
  styles/books/hs-physics/book.scss
  styles/designs/carnival/parts/_eoc-components.scss
  styles/designs/carnival/parts/_eoc-shapes.scss
  styles/output/_web-styles.json
  styles/output/hs-physics-pdf.css
  styles/output/hs-physics-pdf.css.map
  styles/output/hs-physics-rex-web.css
  styles/output/hs-physics-rex-web.css.map
  styles/templates/template1/parts/_eoc-settings.scss
Labels: review:Anna

#1697 apbiology: add space margin-bottom nested lists exercises
  styles/designs/carnival/parts/_answerkey-components.scss
  styles/designs/carnival/parts/_appendix-components.scss
  styles/designs/carnival/parts/_appendix-shapes.scss
  styles/designs/carnival/parts/_eoc-components.scss
  styles/designs/carnival/parts/_eoc-shapes.scss
  styles/designs/carnival/parts/_module-components.scss
  styles/designs/carnival/parts/_module-shapes.scss
  styles/designs/carnival/parts/_preface-components.scss
  styles/designs/carnival/parts/_preface-shapes.scss
  styles/designs/carnival/parts/notes/_notes-boxed-shapes.scss
  styles/designs/carnival/parts/notes/_notes-components.scss
  styles/designs/carnival/parts/notes/_notes-icon-shapes.scss
  styles/designs/carnival/parts/notes/_notes-iconCondensed-shapes.scss
  styles/designs/common/_reset.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/ap-biology-pdf.css
  styles/output/ap-biology-pdf.css.map
  styles/output/ap-biology-rex-web.css
  styles/output/ap-biology-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/output/hs-physics-pdf.css
  styles/output/hs-physics-pdf.css.map
  styles/output/hs-physics-rex-web.css
  styles/output/hs-physics-rex-web.css.map
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/microbiology-rex-web.css
  styles/output/microbiology-rex-web.css.map
  styles/output/physics-pdf.css
  styles/output/physics-pdf.css.map
  styles/output/physics-rex-web.css
  styles/output/physics-rex-web.css.map
  styles/output/u-physics-pdf.css
  styles/output/u-physics-pdf.css.map
  styles/output/u-physics-rex-web.css
  styles/output/u-physics-rex-web.css.map
  styles/templates/template1/parts/_eoc-settings.scss
Labels: book:ap.biology, review:Alan, review:BrittanyJ

#1835 Style notes in hs physics
  recipes/books/hs-physics/_config.scss
  recipes/output/hs-physics.css
  styles/books/hs-physics/book.scss
  styles/books/u-physics/book.scss
  styles/designs/carnival/parts/notes/_notes-boxedCondensed-shapes.scss
  styles/designs/carnival/parts/notes/_notes-components.scss
  styles/designs/carnival/parts/notes/_notes-icon-shapes.scss
  styles/designs/carnival/resources/carnival-boundlessphysics.svg
  styles/designs/carnival/resources/carnival-funphysics.svg
  styles/output/_web-styles.json
  styles/output/hs-physics-pdf.css
  styles/output/hs-physics-pdf.css.map
  styles/output/hs-physics-rex-web.css
  styles/output/hs-physics-rex-web.css.map
  styles/output/u-physics-pdf.css.map
  styles/output/u-physics-rex-web.css.map
  styles/templates/template1/_colors.scss
Labels: review:Anna, review:BrittanyJ

#1851 Section exercises in hs physics
  recipes/books/hs-physics/_config.scss
  recipes/output/hs-physics.css
  styles/books/hs-physics/book.scss
  styles/designs/carnival/parts/_exercises-components.scss
  styles/designs/carnival/parts/_exercises-shapes.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css.map
  styles/output/ap-biology-pdf.css.map
  styles/output/ap-biology-rex-web.css.map
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css.map
  styles/output/hs-physics-pdf.css
  styles/output/hs-physics-pdf.css.map
  styles/output/hs-physics-rex-web.css
  styles/output/hs-physics-rex-web.css.map
  styles/output/microbiology-pdf.css.map
  styles/output/microbiology-rex-web.css.map
  styles/output/physics-pdf.css.map
  styles/output/physics-rex-web.css.map
  styles/output/u-physics-pdf.css.map
  styles/output/u-physics-rex-web.css.map
  styles/templates/template1/_design.scss
  styles/templates/template1/_settings.scss
  styles/templates/template1/parts/_exercises-settings.scss
Labels: review:Anna

#1864 Grasp Check title
  recipes/books/_common-stuff.scss
  recipes/books/_generator.scss
  recipes/books/hs-physics/_config.scss
  recipes/locale/pl/_common-stuff.scss
  recipes/mixins/_modify.scss
  recipes/output/hs-physics.css
  styles/output/_web-styles.json
Labels: review:Anna

#1838 Issue 1797
  styles/designs/common/pdf/_grid.scss
  styles/output/anatomy-pdf.css
  styles/output/anatomy-rex-web.css
  styles/output/ap-biology-pdf.css
  styles/output/ap-biology-rex-web.css
  styles/output/biology-pdf.css
  styles/output/biology-rex-web.css
  styles/output/chemistry-pdf.css
  styles/output/chemistry-rex-web.css
  styles/output/hs-physics-pdf.css
  styles/output/hs-physics-rex-web.css
  styles/output/microbiology-pdf.css
  styles/output/microbiology-rex-web.css
  styles/output/physics-pdf.css
  styles/output/physics-rex-web.css
  styles/output/u-physics-pdf.css
  styles/output/u-physics-rex-web.css
  styles/templates/template1/parts/_table-settings.scss
Labels: review:Anna

#1868 applied Natalia's styling from #1463 to Bio, Phys, and hsPhys
  RELEASE_FLAGS.md
  recipes/books/_release.scss
  recipes/books/biology/_config.scss
  recipes/books/hs-physics/_config.scss
  recipes/books/physics/_config.scss
  styles/books/biology/book.scss
  styles/books/hs-physics/book.scss
  styles/books/physics/book.scss
  styles/output/ap-biology-pdf.css
  styles/output/ap-biology-rex-web.css
  styles/output/biology-pdf.css
  styles/output/biology-rex-web.css
  styles/output/hs-physics-pdf.css
  styles/output/hs-physics-rex-web.css
  styles/output/physics-pdf.css
  styles/output/physics-rex-web.css
  styles/templates/template1/_colors.scss
Labels: review:Anna

#1859 Remove border and padding/margin on module titles, remove padding below learning objectives ul
  styles/books/hs-physics/book.scss
  styles/designs/carnival/parts/_eoc-components.scss
  styles/designs/carnival/parts/_eoc-shapes.scss
  styles/designs/carnival/parts/_learning-components.scss
  styles/designs/carnival/parts/_module-components.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/ap-biology-pdf.css
  styles/output/ap-biology-pdf.css.map
  styles/output/ap-biology-rex-web.css
  styles/output/ap-biology-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/output/hs-physics-pdf.css
  styles/output/hs-physics-pdf.css.map
  styles/output/hs-physics-rex-web.css
  styles/output/hs-physics-rex-web.css.map
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/microbiology-rex-web.css
  styles/output/microbiology-rex-web.css.map
  styles/output/physics-pdf.css
  styles/output/physics-pdf.css.map
  styles/output/physics-rex-web.css
  styles/output/physics-rex-web.css.map
  styles/output/u-physics-pdf.css
  styles/output/u-physics-pdf.css.map
  styles/output/u-physics-rex-web.css
  styles/output/u-physics-rex-web.css.map
  styles/templates/template1/parts/_eoc-settings.scss
Labels: review:Anna

#1866 Change intro title to float, remove intro first paragraph's component
  styles/designs/carnival/parts/_chapterintro-components.scss
  styles/designs/carnival/parts/_chapterintro-shapes.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/ap-biology-pdf.css
  styles/output/ap-biology-pdf.css.map
  styles/output/ap-biology-rex-web.css
  styles/output/ap-biology-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/output/hs-physics-pdf.css
  styles/output/hs-physics-pdf.css.map
  styles/output/hs-physics-rex-web.css
  styles/output/hs-physics-rex-web.css.map
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/microbiology-rex-web.css
  styles/output/microbiology-rex-web.css.map
  styles/output/physics-pdf.css
  styles/output/physics-pdf.css.map
  styles/output/physics-rex-web.css
  styles/output/physics-rex-web.css.map
  styles/output/u-physics-pdf.css
  styles/output/u-physics-pdf.css.map
  styles/output/u-physics-rex-web.css
  styles/output/u-physics-rex-web.css.map
Labels: review:Alan, review:Anna

#1871 Page numbering
  styles/designs/common/pdf/_folio.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/ap-biology-pdf.css
  styles/output/ap-biology-pdf.css.map
  styles/output/ap-biology-rex-web.css
  styles/output/ap-biology-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/output/hs-physics-pdf.css
  styles/output/hs-physics-pdf.css.map
  styles/output/hs-physics-rex-web.css
  styles/output/hs-physics-rex-web.css.map
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/microbiology-rex-web.css
  styles/output/microbiology-rex-web.css.map
  styles/output/physics-pdf.css
  styles/output/physics-pdf.css.map
  styles/output/physics-rex-web.css
  styles/output/physics-rex-web.css.map
  styles/output/u-physics-pdf.css
  styles/output/u-physics-pdf.css.map
  styles/output/u-physics-rex-web.css
  styles/output/u-physics-rex-web.css.map
Labels: review:Anna

#1856 Figures center
  styles/designs/carnival/parts/_figureimage-components.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/ap-biology-pdf.css
  styles/output/ap-biology-pdf.css.map
  styles/output/ap-biology-rex-web.css
  styles/output/ap-biology-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/output/hs-physics-pdf.css
  styles/output/hs-physics-pdf.css.map
  styles/output/hs-physics-rex-web.css
  styles/output/hs-physics-rex-web.css.map
  styles/output/physics-pdf.css
  styles/output/physics-pdf.css.map
  styles/output/physics-rex-web.css
  styles/output/physics-rex-web.css.map
  styles/output/u-physics-pdf.css
  styles/output/u-physics-pdf.css.map
  styles/output/u-physics-rex-web.css
  styles/output/u-physics-rex-web.css.map
Labels: book:biology.2e

#1877 Disable web styles
  books.txt
  script/build-styles
  styles/output/apbiology-pdf.css
  styles/output/apbiology-pdf.css.map
  styles/output/apbiology-rex-web.css
  styles/output/apbiology-rex-web.css.map
  styles/output/generic-pdf.css.map
  styles/output/intro-business-pdf.css.map
Labels: review: Natalia, review:Anna

#1879 Add paragraph title component and add spacing to it
  styles/designs/carnival/parts/_module-components.scss
  styles/designs/carnival/parts/_module-shapes.scss
  styles/output/_web-styles.json
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anatomy-rex-web.css
  styles/output/anatomy-rex-web.css.map
  styles/output/ap-biology-pdf.css
  styles/output/ap-biology-pdf.css.map
  styles/output/ap-biology-rex-web.css
  styles/output/ap-biology-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/output/hs-physics-pdf.css
  styles/output/hs-physics-pdf.css.map
  styles/output/hs-physics-rex-web.css
  styles/output/hs-physics-rex-web.css.map
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/microbiology-rex-web.css
  styles/output/microbiology-rex-web.css.map
  styles/output/physics-pdf.css
  styles/output/physics-pdf.css.map
  styles/output/physics-rex-web.css
  styles/output/physics-rex-web.css.map
  styles/output/u-physics-pdf.css
  styles/output/u-physics-pdf.css.map
  styles/output/u-physics-rex-web.css
  styles/output/u-physics-rex-web.css.map
Labels: review:Anna

#1867 chapter outline new design
  styles/books/physics/book.scss
  styles/designs/carnival/parts/_chapterintro-components.scss
  styles/designs/carnival/parts/_chapterintro-shapes.scss
  styles/output/_web-styles.json
  styles/output/physics-pdf.css
  styles/output/physics-pdf.css.map
  styles/output/physics-rex-web.css
  styles/output/physics-rex-web.css.map
  styles/templates/template1/parts/_chapterintro-settings.scss
Labels: review:BrittanyJ

#1881 remove bullets from data-bullet-style:none lists
  styles/designs/carnival/parts/_table-components.scss
  styles/designs/carnival/parts/_table-shapes.scss
  styles/output/_web-styles.json
  styles/output/ap-biology-pdf.css
  styles/output/ap-biology-pdf.css.map
  styles/output/ap-biology-rex-web.css
  styles/output/ap-biology-rex-web.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/biology-rex-web.css
  styles/output/biology-rex-web.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/chemistry-rex-web.css
  styles/output/chemistry-rex-web.css.map
  styles/output/hs-physics-pdf.css
  styles/output/hs-physics-pdf.css.map
  styles/output/hs-physics-rex-web.css
  styles/output/hs-physics-rex-web.css.map
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/microbiology-rex-web.css
  styles/output/microbiology-rex-web.css.map
  styles/output/physics-pdf.css
  styles/output/physics-pdf.css.map
  styles/output/physics-rex-web.css
  styles/output/physics-rex-web.css.map
  styles/output/u-physics-pdf.css
  styles/output/u-physics-pdf.css.map
  styles/output/u-physics-rex-web.css
  styles/output/u-physics-rex-web.css.map
Labels: book:biology.2e

#1892 Folios
  styles/designs/common/pdf/_folio.scss
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/ap-biology-pdf.css
  styles/output/ap-biology-pdf.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/hs-physics-pdf.css
  styles/output/hs-physics-pdf.css.map
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/physics-pdf.css
  styles/output/physics-pdf.css.map
  styles/output/u-physics-pdf.css
  styles/output/u-physics-pdf.css.map
Labels: review:Anna

#1894 Change font-scale
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/ap-biology-pdf.css
  styles/output/ap-biology-pdf.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/hs-physics-pdf.css
  styles/output/hs-physics-pdf.css.map
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/physics-pdf.css
  styles/output/physics-pdf.css.map
  styles/output/u-physics-pdf.css
  styles/output/u-physics-pdf.css.map
  styles/templates/template1/parts/_toc-settings.scss
Labels: review:Alan, review:Anna

#1915 update locked recipe
  recipes/output/entrepreneurship-prod.css
Labels: review:Helene

#1897 Add data-uuid-key to composite chapters
  recipes/mixins/_compose.scss
  recipes/output/astronomy.css
  recipes/output/dev-math.css
  recipes/output/hs-physics.css
  recipes/output/microbiology.css
  recipes/output/pl-u-physics.css
  recipes/output/u-physics.css
Labels: review:Anna

#1913 Bleed with streched image
  styles/books/anatomy/book.scss
  styles/books/biology/book.scss
  styles/books/chemistry/book.scss
  styles/books/hs-physics/book.scss
  styles/books/physics/book.scss
  styles/books/u-physics/book.scss
  styles/designs/carnival/parts/_chapterintro-components.scss
  styles/designs/common/pdf/_bleed.scss
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/ap-biology-pdf.css
  styles/output/ap-biology-pdf.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/hs-physics-pdf.css
  styles/output/hs-physics-pdf.css.map
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/physics-pdf.css
  styles/output/physics-pdf.css.map
  styles/output/u-physics-pdf.css
  styles/output/u-physics-pdf.css.map
  styles/templates/template1/_design.scss
  styles/templates/template1/parts/_chapterintro-settings.scss
Labels: review:Anna

#1917 reduce margins after eoc cntainer
  styles/designs/carnival/parts/_eoc-components.scss
  styles/output/anatomy-pdf.css
  styles/output/ap-biology-pdf.css
  styles/output/biology-pdf.css
  styles/output/chemistry-pdf.css
  styles/output/hs-physics-pdf.css
  styles/output/microbiology-pdf.css
  styles/output/physics-pdf.css
Labels: review:Alan, review:Anna

#1921 Issue 1827 - Single Column Tables
  styles/designs/carnival/parts/_table-components.scss
  styles/designs/carnival/parts/_table-shapes.scss
  styles/output/anatomy-pdf.css
  styles/output/ap-biology-pdf.css
  styles/output/biology-pdf.css
  styles/output/chemistry-pdf.css
  styles/output/hs-physics-pdf.css
  styles/output/microbiology-pdf.css
  styles/output/physics-pdf.css
  styles/output/u-physics-pdf.css
  styles/templates/template1/parts/_table-settings.scss
Labels: review:Anna

#1902 Fix introduction
  recipes/books/_common-stuff.scss
  recipes/books/hs-physics/_config.scss
  recipes/mixins/_modify.scss
  recipes/output/hs-physics.css
  styles/books/hs-physics/book.scss
  styles/output/anatomy-pdf.css.map
  styles/output/ap-biology-pdf.css.map
  styles/output/biology-pdf.css.map
  styles/output/chemistry-pdf.css.map
  styles/output/hs-physics-pdf.css
  styles/output/hs-physics-pdf.css.map
  styles/output/microbiology-pdf.css.map
  styles/output/physics-pdf.css.map
  styles/output/u-physics-pdf.css.map
Labels: review:Alan

#1924 add labelText phet note college physics
  recipes/books/physics/_config.scss
  recipes/output/physics.css
Labels: book:college.physics, review:Alan

#1934 Add slice to condensed icon
  styles/designs/carnival/parts/notes/_notes-components.scss
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/ap-biology-pdf.css
  styles/output/ap-biology-pdf.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/hs-physics-pdf.css
  styles/output/hs-physics-pdf.css.map
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/physics-pdf.css
  styles/output/physics-pdf.css.map
  styles/output/u-physics-pdf.css
  styles/output/u-physics-pdf.css.map
Labels: review:Anna

#1930 add attribution link on every other page
  styles/designs/common/pdf/_folio.scss
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/ap-biology-pdf.css
  styles/output/ap-biology-pdf.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/hs-physics-pdf.css
  styles/output/hs-physics-pdf.css.map
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/physics-pdf.css
  styles/output/physics-pdf.css.map
  styles/output/u-physics-pdf.css
  styles/output/u-physics-pdf.css.map
Labels: baked.styles, review:Alan, review:BrittanyJ

#1940 key equations tables alignement hs physics
  styles/books/hs-physics/book.scss
  styles/designs/carnival/parts/_eoc-components.scss
  styles/designs/carnival/parts/_eoc-shapes.scss
  styles/output/hs-physics-pdf.css
  styles/output/hs-physics-pdf.css.map
  styles/templates/template1/parts/_eoc-settings.scss
Labels: book:physics, review:Alan

#1925 Suppress answerkey in Biology Anatomy
  recipes/books/anatomy/_config.scss
  recipes/books/biology/_config.scss
  recipes/output/anatomy.css
  recipes/output/biology.css
  styles/books/anatomy/book.scss
  styles/books/biology/book.scss
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/ap-biology-pdf.css
  styles/output/ap-biology-pdf.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
Labels: book:anatomy.and.physiology, book:biology.2e, book:concepts.biology

#1941 fix enable top tiled tables feature biology-2e
  recipes/books/biology/_config.scss
  recipes/output/ap-biology.css
  recipes/output/biology.css
Labels: book:biology.2e

#1958 add labelText to Problem solving strategy note uphysics
  recipes/books/u-physics/_config.scss
  recipes/output/u-physics.css
Labels: book:university.physics

#1963 Remove line in page breaks for boxed icons
  styles/designs/carnival/parts/notes/_notes-components.scss
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/ap-biology-pdf.css
  styles/output/ap-biology-pdf.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/u-physics-pdf.css
  styles/output/u-physics-pdf.css.map
Labels: review:Anna

#1966 enable all feature flags uphysics
  RELEASE_FLAGS.md
  recipes/books/_release.scss
  recipes/output/u-physics.css
Labels: book:university.physics

#1946 Enable chapters labels numbers units toc
  recipes/README.md
  recipes/books/_common-stuff.scss
  recipes/books/_generator.scss
  recipes/locale/pl/_common-stuff.scss
  recipes/mixins/_count.scss
  recipes/mixins/_number.scss
  recipes/output/accounting.css
  recipes/output/american-government.css
  recipes/output/anatomy.css
  recipes/output/ap-biology.css
  recipes/output/ap-history.css
  recipes/output/ap-physics.css
  recipes/output/astronomy.css
  recipes/output/biology.css
  recipes/output/business-ethics.css
  recipes/output/calculus.css
  recipes/output/chemistry.css
  recipes/output/college-success.css
  recipes/output/dev-math.css
  recipes/output/economics.css
  recipes/output/entrepreneurship.css
  recipes/output/history.css
  recipes/output/hs-physics.css
  recipes/output/intro-business.css
  recipes/output/microbiology.css
  recipes/output/physics.css
  recipes/output/pl-u-physics.css
  recipes/output/precalculus.css
  recipes/output/principles-management.css
  recipes/output/psychology.css
  recipes/output/sociology.css
  recipes/output/statistics.css
  recipes/output/u-physics.css
  styles/designs/carnival/parts/_toc-components.scss
Labels: review:Alan
