Repository openstax/cnx-recipes, pull requests merged in 2021-08, with the labels that each got.

#4055 add numbered learning objectives settings
  recipes/books/bca/_config.scss
  styles/books/bca/book.scss
  styles/design-settings/cardboard/parts/_learning-settings.scss
  styles/designs/cardboard/parts/_learning-components.scss
  styles/output/additive-manufacturing-pdf.css
  styles/output/additive-manufacturing-pdf.css.map
  styles/output/anatomy-pdf.css
  styles/output/anatomy-pdf.css.map
  styles/output/anthropology-pdf.css
  styles/output/anthropology-pdf.css.map
  styles/output/ap-biology-pdf.css
  styles/output/ap-biology-pdf.css.map
  styles/output/ap-physics-pdf.css
  styles/output/ap-physics-pdf.css.map
  styles/output/bca-pdf.css
  styles/output/bca-pdf.css.map
  styles/output/biology-pdf.css
  styles/output/biology-pdf.css.map
  styles/output/calculus-pdf.css
  styles/output/calculus-pdf.css.map
  styles/output/chemistry-pdf.css
  styles/output/chemistry-pdf.css.map
  styles/output/college-physics-pdf.css
  styles/output/college-physics-pdf.css.map
  styles/output/contemporary-math-pdf.css
  styles/output/contemporary-math-pdf.css.map
  styles/output/dev-math-pdf.css
  styles/output/dev-math-pdf.css.map
  styles/output/hs-physics-pdf.css
  styles/output/hs-physics-pdf.css.map
  styles/output/microbiology-pdf.css
  styles/output/microbiology-pdf.css.map
  styles/output/precalculus-coreq-pdf.css
  styles/output/precalculus-coreq-pdf.css.map
  styles/output/precalculus-pdf.css
  styles/output/precalculus-pdf.css.map
  styles/output/statistics-pdf.css
  styles/output/statistics-pdf.css.map
Labels: review.request:1

#4059 link to learning subtitle
  styles/books/finance/book.scss
  styles/output/finance-pdf.css
  styles/output/finance-pdf.css.map
Labels: review.request:1

#4064 Point pl-psychology to production
  books.txt
Labels: book:psychologia

#4070 style contemporary math's injected exercises
  styles/books/contemporary-math/book.scss
  styles/design-settings/corn/parts/_lists-settings.scss
  styles/designs/corn/parts/_answerkey-shapes.scss
  styles/designs/corn/parts/_exercises-components.scss
  styles/designs/corn/parts/_exercises-shapes.scss
  styles/designs/corn/parts/_lists-components.scss
  styles/designs/corn/parts/_lists-shapes.scss
  styles/output/calculus-pdf.css
  styles/output/calculus-pdf.css.map
  styles/output/contemporary-math-pdf.css
  styles/output/contemporary-math-pdf.css.map
  styles/output/dev-math-pdf.css
  styles/output/dev-math-pdf.css.map
  styles/output/precalculus-coreq-pdf.css
  styles/output/precalculus-coreq-pdf.css.map
  styles/output/precalculus-pdf.css
  styles/output/precalculus-pdf.css.map
  styles/output/statistics-pdf.css
  styles/output/statistics-pdf.css.map
Labels: review.request:2

#4078 Style video activity source notes: finance
  styles/books/finance/book.scss
  styles/designs/cardboard/resources/cardboard-media.svg
  styles/output/finance-pdf.css
  styles/output/finance-pdf.css.map
Labels: book:introduction.finance
